// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWLhihde1fUA-5m7ZOjWj57VSsjRv4NA',
    appId: '1:772944741867:web:0be91abe8e61cc63d085ae',
    messagingSenderId: '772944741867',
    projectId: 'tugaspab2-d388b',
    authDomain: 'tugaspab2-d388b.firebaseapp.com',
    databaseURL: 'https://tugaspab2-d388b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2-d388b.firebasestorage.app',
    measurementId: 'G-9B5KB49ZJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJ5ASih9OcLhAY_ghE575XuxcscVlqLg',
    appId: '1:772944741867:android:0ad14241d2b4845bd085ae',
    messagingSenderId: '772944741867',
    projectId: 'tugaspab2-d388b',
    databaseURL: 'https://tugaspab2-d388b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2-d388b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-0zr6vsDV04shQHOfbae_AKYB3hwJ5Ls',
    appId: '1:772944741867:ios:d152fbb3a8403772d085ae',
    messagingSenderId: '772944741867',
    projectId: 'tugaspab2-d388b',
    databaseURL: 'https://tugaspab2-d388b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2-d388b.firebasestorage.app',
    iosBundleId: 'com.example.mahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-0zr6vsDV04shQHOfbae_AKYB3hwJ5Ls',
    appId: '1:772944741867:ios:d152fbb3a8403772d085ae',
    messagingSenderId: '772944741867',
    projectId: 'tugaspab2-d388b',
    databaseURL: 'https://tugaspab2-d388b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2-d388b.firebasestorage.app',
    iosBundleId: 'com.example.mahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLWLhihde1fUA-5m7ZOjWj57VSsjRv4NA',
    appId: '1:772944741867:web:4538930018614ed8d085ae',
    messagingSenderId: '772944741867',
    projectId: 'tugaspab2-d388b',
    authDomain: 'tugaspab2-d388b.firebaseapp.com',
    databaseURL: 'https://tugaspab2-d388b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tugaspab2-d388b.firebasestorage.app',
    measurementId: 'G-C2DG9HEYSN',
  );
}
